### ISSUE TITLE
how to get ./tensorflow_model_server

### ISSUE THREAD

**Issue by joyJZhang** [tobegit3hub/deep_image_model#1]
hello ,when I Run TensorFlow serving,I found this
root@3a676eb847d1:/java/deep_cnn-master# bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=deep_cnn --model_base_path=./model
bash: bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server: **No such file or directory**
how to get the ./tensorflow_model_server?Thank you ~~

**Comment by tobegit3hub** [comment]
You can build from [tensorflow/serving]() project with `bazel`.

If you're using x64 Linux, you can download this binary from https://pan.baidu.com/s/1eSzFp9C which is build on Linux server.

Hope it helps :)
