### ISSUE TITLE
java client can not Connect

### ISSUE THREAD

**Issue by joyJZhang** [tobegit3hub/deep_image_model#2]
hello ,I run tensorflow server in docker ,and it run successfully.
**I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:252] File-system polling update: Servable:{name: deep_cnn version: 1}; Servable path: ./model/00000001; Polling frequency: 30**
But when I run java client (not in docker,in local),it has an error.
**警告: RPC failed: Status{code=UNAVAILABLE, description=null, cause=java.net.ConnectException: Connection refused: /127.0.0.1:9000}**
And I try to run python client in docker ,it runs successfully.
Does this have relationship with docker? Otherwise why cann't they connect.
thank you very much~~

**Comment by tobegit3hub** [comment]
It seems that you're not able to connect with `127.0.0.1:9000`.

How do you run your docker container? Have you exposed the port of 9000 by `-p` parameter?

Try `docker run` with `-p 9000:9000` and it should work.

**Comment by joyJZhang** [comment]
thank you !! I checked my docker container,found its ports is 0.0.0.0:8889->8889/tcp.I change 9000 to 8889,and it run :)

**Comment by tobegit3hub** [comment]
Well. It's my pleasure to help 😃
