### ISSUE TITLE
guava version

### ISSUE THREAD

**Issue by joyJZhang** [tobegit3hub/deep_image_model#4]
hello,when i run java client ,i found this
**java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects**
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:257)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:69)
and i did not find MoreObjects in guava14.0,so should i download guava 19.0?i downloaded a guava19.0,but somtimes it tried to find MoreObjects in 14.0.what should i do ?thank you ~~~

**Comment by joyJZhang** [comment]
I solved the problem  .add dependencies like <dependencyManagement> ...19.0  ...</dependencyManagement>

**Comment by tobegit3hub** [comment]
Nice work @joyJZhang 

But I think all the dependencies have been add in `pom.xml` and users don't need to configure anything for compiling and running with `maven`. What's the problem about `guava` and should we add more instruction about this?

**Comment by joyJZhang** [comment]
I checked again，found that your project is complete。It is my fault. I add   <parent> in pom.xml ,<parent> has guava14，and yours has 19，they clash.when i invoke  a method ,it always try to find in 14~~

**Comment by tobegit3hub** [comment]
Great and thanks for your feedback 😃
