### ISSUE TITLE
create 3 servings  in a docker container

### ISSUE THREAD

**Issue by joyJZhang** [tobegit3hub/deep_image_model#5]
hello~~
I need to use the 3 models to identify 3 kinds of pictures and I want to provide these 3 service in a  container,How can I solve this problem?
I created a container like this " **docker run -it -p 7770:7770 -p 7771:7771 -p 7772:7772 _card_ /bin/bash**"
provide 3 ports,and used **ENTRYPOINT ["_card_"]** to run the 3 commands like this"./tensorflow_model_server —port=7770 --model_name=simple1 --model_base_path=./simple1",But I saw it just run the first commands.

**Comment by tobegit3hub** [comment]
As far as I known, you want to inference for 3 pictures, just like identifying 3 classification. If so, you don't need to setup 3 service, just use one `tensorflow_model_server` to load that model and run in docker.

**Comment by joyJZhang** [comment]
so,how to use  one tensorflow_model_server to load 3 models?and does one model corresponde to a port ？use command like this？**./tensorflow_model_server --port=9000 --model_name=deep_cnn --model_base_path=./model**thank you~~~~

**Comment by tobegit3hub** [comment]
One TensorFlow Serving can not load multiple models or expose multiple ports.

You need to run 3 `tensorflow_model_server` for 3 models in 3 docker containers with different ports.

**Comment by joyJZhang** [comment]
I used Dockerfile **ENTRYPOINT["./card"]** and put 3 commands in card ,then **docke build -t card .**  **docker run -it -p 6660:6660 -p 6661:6661 -p 6662:6662 card /bin/bash**
And it can run 3 tensorflow_model_server for 3 models in 1 docker containers with different ports.
The reason why I can not run successful this morning is that I write commands wrong in card.

**Comment by tobegit3hub** [comment]
So it's your problem to write the script to run 3 TensorFlow Serving processes in one container.

By the way, I won't say it's the best practice to use TensorFlow Serving or Docker. You can setup 3 containers for this task and it's much easier to maintain and scala.
