### ISSUE TITLE
The client maximum number of requests at the same time

### ISSUE THREAD

**Issue by joyJZhang** [tobegit3hub/deep_image_model#6]
hello,I provide a tensorflow serving ,and use java client to use it.how many clients can request this service at the same time ,Is there any quantity limitation for the this？thank you

**Comment by tobegit3hub** [comment]
It's the standard gRPC server and you can change some parameters about that. I don't think it's flexible to limit the requests of each client. If you want to do that, you may implement your API services upon TensorFlow Serving.

**Comment by tobegit3hub** [comment]
Close and won't fix.

Feel free to re-open if you have any other question. 😃
